URL_SERVICE = "https://cnt-c8e3e82e-2658-445f-98c8-9bb20cbb3dbf.containerhub.tripleten-services.com/"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"